name: Lint and Publish
on: push
permissions: write-all
jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm i
          npm run lint
  publish:
    name: publish package
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - uses: JS-DevTools/npm-publish@v1
        with:
          registry: https://npm.pkg.github.com
          token: ${{ secrets.GITHUB_TOKEN }}
